---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - check_uptime
    - copy_logfile
    - restart_service
    - send_mail
